[mypy]
python_version = 3.11
allow_redefinition = False
check_untyped_defs = True
disallow_untyped_defs = True
ignore_errors = False
ignore_missing_imports = True
implicit_reexport = False
local_partial_types = True
no_implicit_optional = True
no_implicit_reexport = True
show_error_codes = True
strict_equality = True
strict_optional = True
warn_redundant_casts = True
warn_unreachable = True
warn_unused_configs = True
warn_unused_ignores = True
plugins = mypy_django_plugin.main,pydantic.mypy

[mypy.plugins.django-stubs]
django_settings_module = config.settings.test

[mypy-*.migrations.*]
# Django migrations should not produce any errors:
ignore_errors = True
